version: '3.8'
services:
  bot:
    build:
      context: .
      dockerfile: apps/bot/Dockerfile
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
  # db:
  #   image: postgres:14.1-alpine
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   ports:
  #     - '5432:5432'
  #   volumes:
  #     - db:/var/lib/postgresql/data
# volumes:
#   db:
#     driver: local
